services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-educlinic}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "${PORT:-4000}:4000"
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=${NODE_ENV:-DEVELOPMENT}
  #     - HOST=0.0.0.0
  #     - PORT=${PORT:-4000}
  #     - DATABASE_URL=${DOCKER_DATABASE_URL:-postgresql://${POSTGRES_USER:-educlinic}:${POSTGRES_PASSWORD:-pass123}@db:5432/${POSTGRES_DB:-educlinic}}
  #     - REDIS_HOST=${DOCKER_REDIS_HOST:-redis}
  #     - REDIS_PORT=${REDIS_PORT:-6379}
  #     - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-supersecretjwtkey12345}
  #     - JWT_TOKEN_EXPIRY=${JWT_TOKEN_EXPIRY:-86400}
  #     - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
  #     - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
  #     - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
