apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: educlinic-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:alumniconnect4/educlinic.git'
    targetRevision: HEAD
    path: educlinic/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
