apiVersion: apps/v1
kind: Deployment
metadata:
  name: educlinic-backend
  labels:
    app: educlinic-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/alumniconnect4/educlinic-backend:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: educlinic-backend
  template:
    metadata:
      labels:
        app: educlinic-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/alumniconnect4/educlinic-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "PRODUCTION"
        - name: DATABASE_URL
          value: "postgresql://educlinic:pass123@host.minikube.internal:5432/educlinic"
        - name: REDIS_HOST
          value: "host.minikube.internal"
        - name: KAFKA_BROKERS
          value: "kafka-svc:9092"
        envFrom:
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: educlinic-backend-svc
spec:
  selector:
    app: educlinic-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
