apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
  - ingress.yaml
  - kafka.yaml
images:
  - name: ghcr.io/alumniconnect4/educlinic-backend
    newName: ghcr.io/alumniconnect4/educlinic-backend
    newTag: latest
